UPLOAD_TO_STAGE_SQL = """
PUT 'file:///opt/airflow/data/Airline Dataset.csv' @AIRLINE_DWH.UTILS.FILES_STAGE 
AUTO_COMPRESS=FALSE 
OVERWRITE=TRUE;
"""

COPY_INTO_TABLE_SQL = "CALL AIRLINE_DWH.RAW_DATA.SP_LOAD_FLIGHTS_RAW();"
CALL_CORE_PROC_SQL = "CALL AIRLINE_DWH.CORE_DATA.SP_PROCESS_RAW_TO_CORE();"
CALL_MARTS_PROC_SQL = "CALL AIRLINE_DWH.DATA_MARTS.SP_UPDATE_MART_AIRPORT_PERF();"