USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE AIRLINE_DWH_ROLE;
GRANT ROLE AIRLINE_DWH_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE AIRLINE_COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE AIRLINE_COMPUTE_WH TO ROLE AIRLINE_DWH_ROLE;

CREATE OR REPLACE DATABASE AIRLINE_DWH;
GRANT OWNERSHIP ON DATABASE AIRLINE_DWH TO ROLE AIRLINE_DWH_ROLE;

USE ROLE AIRLINE_DWH_ROLE;
USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE SCHEMA RAW_DATA;
CREATE OR REPLACE SCHEMA CORE_DATA;
CREATE OR REPLACE SCHEMA DATA_MARTS;
CREATE OR REPLACE SCHEMA UTILS;

USE SCHEMA RAW_DATA;
CREATE OR REPLACE TABLE FLIGHTS_RAW (
    ROW_ID VARCHAR, PASSENGER_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
    GENDER VARCHAR, AGE VARCHAR, NATIONALITY VARCHAR, AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR, COUNTRY_NAME VARCHAR, AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR, DEPARTURE_DATE VARCHAR, ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR, FLIGHT_STATUS VARCHAR, TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM FLIGHTS_STREAM ON TABLE FLIGHTS_RAW;

USE SCHEMA CORE_DATA;
CREATE OR REPLACE TABLE DIM_PASSENGERS (
    PASSENGER_SK NUMBER IDENTITY(1,1) PRIMARY KEY, PASSENGER_REF_ID VARCHAR,
    FIRST_NAME VARCHAR, LAST_NAME VARCHAR, GENDER VARCHAR, AGE NUMBER,
    NATIONALITY VARCHAR, VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), IS_CURRENT BOOLEAN DEFAULT TRUE
);
CREATE OR REPLACE TABLE DIM_AIRPORTS (
    AIRPORT_SK NUMBER IDENTITY(1,1) PRIMARY KEY, AIRPORT_NAME VARCHAR,
    COUNTRY_CODE VARCHAR, COUNTRY_NAME VARCHAR, CONTINENT_CODE VARCHAR, CONTINENT_NAME VARCHAR
);
CREATE OR REPLACE TABLE DIM_PILOTS (
    PILOT_SK NUMBER IDENTITY(1,1) PRIMARY KEY, PILOT_NAME VARCHAR
);
CREATE OR REPLACE TABLE FACT_FLIGHTS (
    FLIGHT_SK NUMBER IDENTITY(1,1) PRIMARY KEY,
    PASSENGER_SK NUMBER REFERENCES DIM_PASSENGERS(PASSENGER_SK),
    DEPARTURE_AIRPORT_SK NUMBER REFERENCES DIM_AIRPORTS(AIRPORT_SK),
    PILOT_SK NUMBER REFERENCES DIM_PILOTS(PILOT_SK),
    ARRIVAL_AIRPORT_CODE VARCHAR, DEPARTURE_DATE DATE,
    FLIGHT_STATUS VARCHAR, TICKET_TYPE VARCHAR, PASSENGER_STATUS VARCHAR
);

USE SCHEMA DATA_MARTS;
CREATE OR REPLACE TABLE RPT_AIRPORT_PERFORMANCE (
    REPORT_DATE DATE, AIRPORT_NAME VARCHAR, COUNTRY_NAME VARCHAR,
    TOTAL_FLIGHTS NUMBER, DELAYED_FLIGHTS NUMBER, CANCELLED_FLIGHTS NUMBER,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA UTILS;
CREATE OR REPLACE TABLE ETL_LOGS (
    LOG_ID NUMBER IDENTITY(1,1), PROCESS_NAME VARCHAR(100),
    LAYER_FROM VARCHAR(50), LAYER_TO VARCHAR(50),
    AFFECTED_ROWS NUMBER, STATUS VARCHAR(20), ERROR_MESSAGE VARCHAR,
    LOG_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE FILE FORMAT CSV_SKIP_HEADER
    TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '') TRIM_SPACE = TRUE ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE FILES_STAGE
    FILE_FORMAT = CSV_SKIP_HEADER DIRECTORY = (ENABLE = TRUE);