USE ROLE AIRLINE_DWH_ROLE;
USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE PROCEDURE RAW_DATA.SP_LOAD_FLIGHTS_RAW()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE AIRLINE_DWH.RAW_DATA.FLIGHTS_RAW;

    COPY INTO AIRLINE_DWH.RAW_DATA.FLIGHTS_RAW
    FROM @AIRLINE_DWH.UTILS.FILES_STAGE
    FILES = ('Airline Dataset.csv')
    FILE_FORMAT = (FORMAT_NAME = AIRLINE_DWH.UTILS.CSV_SKIP_HEADER)
    ON_ERROR = 'CONTINUE';

    COMMIT;
    RETURN 'Raw load successful';
END;
$$;

CREATE OR REPLACE PROCEDURE CORE_DATA.SP_PROCESS_RAW_TO_CORE()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INT DEFAULT 0;
BEGIN
    IF (SYSTEM$STREAM_HAS_DATA('AIRLINE_DWH.RAW_DATA.FLIGHTS_STREAM') = FALSE) THEN
        RETURN 'No new data in stream.';
    END IF;

    BEGIN TRANSACTION;

    MERGE INTO AIRLINE_DWH.CORE_DATA.DIM_PASSENGERS AS T
    USING (SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY FROM AIRLINE_DWH.RAW_DATA.FLIGHTS_STREAM WHERE METADATA$ACTION = 'INSERT') AS S
    ON T.PASSENGER_REF_ID = S.PASSENGER_ID
    WHEN NOT MATCHED THEN INSERT (PASSENGER_REF_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY) VALUES (S.PASSENGER_ID, S.FIRST_NAME, S.LAST_NAME, S.GENDER, S.AGE, S.NATIONALITY);

    MERGE INTO AIRLINE_DWH.CORE_DATA.DIM_AIRPORTS AS T
    USING (SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS FROM AIRLINE_DWH.RAW_DATA.FLIGHTS_STREAM WHERE METADATA$ACTION = 'INSERT') AS S
    ON T.AIRPORT_NAME = S.AIRPORT_NAME
    WHEN NOT MATCHED THEN INSERT (AIRPORT_NAME, COUNTRY_CODE, COUNTRY_NAME, CONTINENT_CODE, CONTINENT_NAME) VALUES (S.AIRPORT_NAME, S.AIRPORT_COUNTRY_CODE, S.COUNTRY_NAME, S.AIRPORT_CONTINENT, S.CONTINENTS);

    MERGE INTO AIRLINE_DWH.CORE_DATA.DIM_PILOTS AS T
    USING (SELECT DISTINCT PILOT_NAME FROM AIRLINE_DWH.RAW_DATA.FLIGHTS_STREAM WHERE METADATA$ACTION = 'INSERT') AS S
    ON T.PILOT_NAME = S.PILOT_NAME
    WHEN NOT MATCHED THEN INSERT (PILOT_NAME) VALUES (S.PILOT_NAME);

    INSERT INTO AIRLINE_DWH.CORE_DATA.FACT_FLIGHTS (PASSENGER_SK, DEPARTURE_AIRPORT_SK, PILOT_SK, ARRIVAL_AIRPORT_CODE, DEPARTURE_DATE, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS)
    SELECT P.PASSENGER_SK, A.AIRPORT_SK, PL.PILOT_SK, S.ARRIVAL_AIRPORT, TRY_TO_DATE(S.DEPARTURE_DATE, 'MM/DD/YYYY'), S.FLIGHT_STATUS, S.TICKET_TYPE, S.PASSENGER_STATUS
    FROM AIRLINE_DWH.RAW_DATA.FLIGHTS_STREAM S
    LEFT JOIN AIRLINE_DWH.CORE_DATA.DIM_PASSENGERS P ON S.PASSENGER_ID = P.PASSENGER_REF_ID
    LEFT JOIN AIRLINE_DWH.CORE_DATA.DIM_AIRPORTS A ON S.AIRPORT_NAME = A.AIRPORT_NAME
    LEFT JOIN AIRLINE_DWH.CORE_DATA.DIM_PILOTS PL ON S.PILOT_NAME = PL.PILOT_NAME
    WHERE S.METADATA$ACTION = 'INSERT';

    rows_inserted := SQLROWCOUNT;
    INSERT INTO AIRLINE_DWH.UTILS.ETL_LOGS (PROCESS_NAME, LAYER_FROM, LAYER_TO, AFFECTED_ROWS, STATUS) VALUES ('SP_PROCESS_RAW_TO_CORE', 'RAW_DATA', 'CORE_DATA', :rows_inserted, 'SUCCESS');

    COMMIT;
    RETURN 'Processed ' || :rows_inserted || ' rows.';
END;
$$;

CREATE OR REPLACE PROCEDURE DATA_MARTS.SP_UPDATE_MART_AIRPORT_PERF()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE AIRLINE_DWH.DATA_MARTS.RPT_AIRPORT_PERFORMANCE;
    INSERT INTO AIRLINE_DWH.DATA_MARTS.RPT_AIRPORT_PERFORMANCE (REPORT_DATE, AIRPORT_NAME, COUNTRY_NAME, TOTAL_FLIGHTS, DELAYED_FLIGHTS, CANCELLED_FLIGHTS)
    SELECT F.DEPARTURE_DATE, A.AIRPORT_NAME, A.COUNTRY_NAME, COUNT(F.FLIGHT_SK), COUNT(CASE WHEN F.FLIGHT_STATUS = 'Delayed' THEN 1 END), COUNT(CASE WHEN F.FLIGHT_STATUS = 'Cancelled' THEN 1 END)
    FROM AIRLINE_DWH.CORE_DATA.FACT_FLIGHTS F
    JOIN AIRLINE_DWH.CORE_DATA.DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_SK = A.AIRPORT_SK
    GROUP BY 1, 2, 3;

    COMMIT;
    RETURN 'Mart updated.';
END;
$$;