USE ROLE AIRLINE_DWH_ROLE;
USE DATABASE AIRLINE_DWH;
USE SCHEMA CORE_DATA;

SELECT * FROM DIM_PASSENGERS
AT(OFFSET => -60*5)
LIMIT 10;

SET my_timestamp = CURRENT_TIMESTAMP();
SELECT * FROM FACT_FLIGHTS
BEFORE(TIMESTAMP => $my_timestamp)
LIMIT 10;

CREATE TABLE TEMP_PILOTS AS SELECT * FROM DIM_PILOTS;
DROP TABLE TEMP_PILOTS;
UNDROP TABLE TEMP_PILOTS;

CREATE OR REPLACE TABLE DIM_PASSENGERS_BACKUP
CLONE DIM_PASSENGERS
AT(OFFSET => -600);