CREATE OR REPLACE ROW ACCESS POLICY RAP_CONTINENT_FILTER
AS (continent_name VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'AIRLINE_DWH_ROLE') THEN TRUE
        WHEN continent_name = 'Europe' THEN TRUE
        ELSE FALSE
    END;

USE ROLE AIRLINE_DWH_ROLE;
USE SCHEMA CORE_DATA;

CREATE OR REPLACE SECURE VIEW V_FLIGHTS_SECURE AS
SELECT
    F.FLIGHT_SK,
    A.CONTINENT_NAME,
    F.FLIGHT_STATUS
FROM FACT_FLIGHTS F
JOIN DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_SK = A.AIRPORT_SK;

USE ROLE SECURITYADMIN;
ALTER VIEW AIRLINE_DWH.CORE_DATA.V_FLIGHTS_SECURE
ADD ROW ACCESS POLICY RAP_CONTINENT_FILTER ON (CONTINENT_NAME);

USE ROLE AIRLINE_DWH_ROLE;
SELECT DISTINCT CONTINENT_NAME FROM V_FLIGHTS_SECURE;